[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["openssl"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]
dependsOn = ["setup"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]
dependsOn = ["install"]

[start]
cmd = "npm run start:prod"
